### ISSUE TITLE
nbextension does not enable clusters tab

### ISSUE THREAD

**Issue by jat255** [ipython/ipyparallel#325]
I have a conda environment, in which I installed `ipyparallel` using `pip install ipyparallel`.

I tried every iteration of `nbextension enable` I found online, but still the "Clusters" tab does not work on my jupyter notebook. It appears that the extension is enabled:

```
[conda_environment] λ jupyter nbextension list
Known nbextensions:
  config dir: C:\anaconda3\envs\conda_environment\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
    tree section
      ipyparallel/main enabled
      - Validating: ok
  config dir: C:\ProgramData\jupyter\nbconfig
    tree section
      ipyparallel/main enabled
      - Validating: ok
```

But when I start up my notebook, I see:

![image](https://user-images.githubusercontent.com/1278301/39318024-fe50c4b4-494a-11e8-9234-8bba0810bbb8.png)

Here is the notebook terminal output, which makes it look like the extension is being loaded:
```
[conda_environment] λ jupyter notebook
[I 12:11:25.173 NotebookApp] Loading IPython parallel extension
[I 12:11:25.424 NotebookApp] Serving notebooks from local directory: C:\Users\username
[I 12:11:25.425 NotebookApp] 0 active kernels
[I 12:11:25.425 NotebookApp] The Jupyter Notebook is running at:
[I 12:11:25.426 NotebookApp] http://localhost:8888/?token=XXXXXXXXXXXXXX
[I 12:11:25.426 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:11:25.430 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=XXXXXXXXXXXXXXXXXXXXXX
[I 12:11:25.817 NotebookApp] Accepting one-time-token-authenticated connection from ::1
```

There is some error in the console, but it doesn't mean much (to me, at least):

```js
Error: Syntax error, unrecognized expression: [href=#clusters]
    at Function.fa.error (jquery.min.js:2)
    at fa.tokenize (jquery.min.js:2)
    at Function.fa [as find] (jquery.min.js:2)
    at n.fn.init.find (jquery.min.js:2)
    at Object.load [as load_ipython_extension] (main.js?v=20180426121124:36)
    at utils.js:39
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.<anonymous> (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
```

**Comment by mirokymac** [comment]
@jat255 The same issue occur on my two linux instances (Ubuntu 16.04). The error you posted is actually matter.
I try to edit the `main.js` in `<Path to your IPyParallel>/share/jupyter/nbextensions/ipyparallel`, replacing `$("#tabs").find('[href=#clusters]').hide()` with `$("#tabs").find('[href="#clusters"]').hide()`. Then re-enable your ipyparallel extension by `ipcluster nbextension enable`. Reload the page and issue fixed.
However, without any patched, the extension tab serving on my Windows laptop can be display well. Any suggestion?

**Comment by qiwei-li** [comment]
I'm seeing the same issue.

**Comment by exowanderer** [comment]
This is still an issue. I have tried almost everything that I read online; but none of the ~10 issues pages have any solutions other than the "uninstall/reinstall".

**Comment by dhoynoski** [comment]
@exowanderer 
Did you try what @mirokymac said above? I found the `main.js` file in the following locations: 
1. C:\Users\NAME\AppData\Local\Programs\Python\Python36-32\share\jupyter\nbextensions\ipyparallel
2. C:\ProgramData\jupyter\nbextensions\ipyparallel
_(The second location may not be present on your desktop?)_

Changing the second location only did not work. However, when I then went to change the first location, it worked. Do exactly what @mirokymac says above:

Find and replace `$("#tabs").find('[href=#clusters]').hide()` 
with the following: `$("#tabs").find('[href="#clusters"]').hide()`
_(Do you notice the new quotes introduced?)_

Then re-enable the ipyparallel extension by running: `ipcluster nbextension enable`.
_(Note: Jupyter Notebook should be shutdown while you are doing all of this)_

Then launch Jupyter Notebook again by running: `jupyter notebook`.

**Comment by minrk** [comment]
I believe this is fixed by #321 in master, which should be released in 6.2.0 shortly.

**Comment by minrk** [comment]
6.2.0 fixes this.

**Comment by exowanderer** [comment]
I just uninstall all of `Jupyter` and `ipyparallel`, then re-installed it and re-setup the configuration using the instructions from `https://github.com/ipython/ipyparallel`.

I now have `ipyparallel version 6.2.1` and `jupyter version 4.4.0`.

The problem is still persisting.

**Comment by minrk** [comment]
@exowanderer ok, since I've verified that it works on a few machines, let's try to get some extra info, since there might be a stale version somewhere:

- platform (mac/windows/etc.)
- Python version
- Python provider (conda, etc.)
- installation method (pip, conda, etc.)
- `pip freeze` output
- `jupyter serverextension list` output
- `jupyter nbextension list` output

Try removing all traces of the extension:

- `pip uninstall ipyparallel`

and check again:

- `jupyter serverextension list`
- `jupyter nbextension list`

After uninstalling, there also shouldn't be any ipyparallel files in:

    $(jupyter --data-dir)/nbextensions

**Comment by exowanderer** [comment]
Good Idea! That's a great list of commands to check. Thank you!  

It works now; I found a solution via your information requests; but here is the path that took me there:

# System Configuration
(1)
Mac OS 10.13.4
Python 3.6.4 :: Anaconda, Inc
Anaconda3-5.1.0-MacOSX x86_64
Conda 4.4.11

(2) Installed via pip (pip install -U ipyparallel)

(3) pip freeze |grep ipyparallel: "ipyparallel==6.2.1"

# Diagnosing the Issues (with your help)
(4) When I first ran `jupyter serverextension list`, there was a yellow warning that `jupyterlab` was not responding; so I uninstalled and reinstalled it.  Now the warning went away and re-running `juypter serverextension list` says 

```python
config dir: /Users/jonathan/.jupyter
    ipyparallel.nbextension  enabled 
    - Validating...
      ipyparallel.nbextension  OK
config dir: /Users/jonathan/anaconda3/etc/jupyter
    ipyparallel.nbextension  enabled 
    - Validating...
      ipyparallel.nbextension  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab  OK
config dir: /usr/local/etc/jupyter
    ipyparallel.nbextension  enabled 
    - Validating...
      ipyparallel.nbextension  OK
```

(5) Running `jupyter nbextension list` flagged a yellow warning about ipyparallel/main disabled

```python
Known nbextensions:
  config dir: /Users/jonathan/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    tree section
      ipyparallel/main disabled  <--**
  config dir: /Users/jonathan/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
    tree section
      ipyparallel/main  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    tree section
      ipyparallel/main  enabled 
      - Validating: OK
```

(6) I ran `pip uninstall ipyparallel`, then checked `$(jupyter --data-dir)`, which still contained `nbextensions/ipyparallel` and `nbextensions/bad_ipyparallel`.  I deleted them both and reinstalled ipyparallel.

Then I re-ran `jupyter nbextension list`, but the `ipyparallel/main` is still listed as `disabled`.  Both before and after I re-installed ipyparallel, I check all of the files in `/Users/jonathan/anaconda3/etc/jupyter/nbconfig`, which said `"ipyparallel/main":true`:

```bash
Cloud:notebooks jonathan$ cat /Users/jonathan/anaconda3/etc/jupyter/nbconfig/*
cat: /Users/jonathan/anaconda3/etc/jupyter/nbconfig/notebook.d: Is a directory
{
  "load_extensions": {
    "jupyter-js-widgets/extension": true
  }
}cat: /Users/jonathan/anaconda3/etc/jupyter/nbconfig/tree.d: Is a directory
{
  "load_extensions": {
    "ipyparallel/main": true
  }
```

# Solution:
I went ahead a wiped out jupyter and ipyparallel from my machine:

`pip uninstall jupyter jupyter-core jupyterlab ipykernel ipyparallel`

then I ran `mdfind jupyter |grep -v STUFF_THAT_DIDNT_MATTER` and wiped out what did matter; primarily:

`rm -rf /Users/jonathan/anaconda3/etc/jupyter/nbconfig`
`rm -rf /Users/jonathan/anaconda3/etc/jupyter`
`rm -rf /Users/jonathan/Library/Jupyter`
`rm -rf /Users/jonathan/.jupyter`

Then I re-installed everything above:

`pip install -U jupyter jupyter-core jupyterlab ipykernel ipyparallel`

Finally, I ran `jupyter notebook` and voilà! the table for `Ipython Clusters` was **fixed**!  Moreover, `jupyter serverextension list` and `jupyter nbextension list` outputs all green!

Thank you for putting in so much effort.  I wrote everything above for someone else who might have such a tenacious problem.

#Side Note:

The directory `~/.jupyter` previously included json files with configurations that included `ipyparallel` information.  It originally said (something like) `"ipyparallel/main":false`; I set this to `true` very early on; but it did not solve anything -- the problem persisted.

**Comment by Shotgunosine** [comment]
I was attempting to install with conda and i was not able to get it to work until I uninstalled via conda, deleted the `ipyparallel` directory from `$(jupyter --data-dir)/nbextensions`, and then reinstalled from conda.

Seems to be working now though.
